# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

obj_value_C <- function(X, y, a, eta, prob) {
    .Call(`_DTRKernSmooth_obj_value_C`, X, y, a, eta, prob)
}

Smooth_C <- function(X, y, a, initial, prob, kn, phi, gamma, err_tol, iter_tol) {
    .Call(`_DTRKernSmooth_Smooth_C`, X, y, a, initial, prob, kn, phi, gamma, err_tol, iter_tol)
}

Boots_C <- function(X, y, a, initial, prob, kn, weights, alpha, phi, gamma, err_tol, iter_tol) {
    .Call(`_DTRKernSmooth_Boots_C`, X, y, a, initial, prob, kn, weights, alpha, phi, gamma, err_tol, iter_tol)
}

